# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- feature/*
- bugfix/*

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
     full_sha=$(Build.SourceVersion)
     sha=${full_sha::8}
     ts=$(date +%s)
     buildId=$(Build.SourceBranchName)-${sha}-${ts}
     echo "BUILD_ID=${buildId}"
     echo "##vso[task.setvariable variable=BUILD_ID]${buildId}"
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Maven@3
  displayName: Build Docker image
  inputs:
    mavenPomFile: 'pom.xml'
    goals: "spring-boot:build-image -Dimage.version=${BUILD_ID}"
    publishJUnitResults: false
    jdkVersionOption: '1.11'
- task: Docker@2
  displayName: Push Docker image
  inputs:
    containerRegistry: 'SandboxSkyklarRegistry'
    repository: 'leveranseplattform/supernova'
    command: 'push'
    tags: '${BUILD_ID}'
