version: "3.1"

services:
    db:
        image: postgres:11.7-alpine 
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-mysecretpassword}
        ports:
            - ${DATABASE_PORT:-5432}:5432
        volumes:
            - db:/var/lib/postgresql/data
    azure-blob:
        image: mcr.microsoft.com/azure-storage/azurite:3.11.0
        restart: always
        ports:
          - 10000:10000
          - 10001:10001

volumes:
    db: {}
