## PostgreSQL
spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: "postgres"
        password: "mysecretpassword"
    jpa:
        hibernate:
            ddl-auto: validate
            #ddl-auto: create-drop # use this for dev if you need to

    flyway:
        out-of-order: true
azure:
    storage:
        connectionstring: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
