create table person (
                        id integer generated by default as identity
                            constraint person_pkey
                                primary key,
                        name varchar(255) not null
);

alter table person owner to postgres;

