# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Supernova github


on:
  push:
    branches: '**'

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - name : Checkout code
      uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        sha=${GITHUB_SHA::8}
        ts=$(date +%s)
        echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build dockerimage
      run: mvn -DskipTests -B spring-boot:build-image -Dimage.version=${{ steps.prep.outputs.BUILD_ID }}
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}   
    - name: 'push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
       docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/leveranseplattform/supernova:${{ steps.prep.outputs.BUILD_ID }}
